# Generated by Django 3.2 on 2021-04-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintask', '0002_auto_20210414_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='studenId',
            new_name='studentId',
        ),
    ]
